### PR TITLE
Add Cpp type, post listing, and C++ blog post.

### PR DESCRIPTION
**Pull request by jeremyong**

### CODE REVIEW

**Comment by tsloughter** [comment]
This could use some more information on your setup. You detail multiple editors but don't describe your preferred editor and plugins. Don't worry about being generic in places like that. It should be about your process.

It would be great to include a unit test, no matter how simple, just to show where you put it and how you run it.

Another important piece is how to share a library or executable with users -- like with Elixir you'd publish to hex, Ruby create a gem and publish, etc. Do you just host it from github as source and if someone wanted to use it as a dependency they'd manually fetch? Does premake provide some fetch/dependency capabilities? Is there a service or tool you use for building cross-arch binaries if that is how you distribute an end user product?

Also, is `#pragma once` so common in C++ it doesn't need a special mention?

**Comment by jeremyong** [comment]
Thanks for the feedback. I'll make edits and resubmit later this weekend.

**Comment by jeremyong** [comment]
OK I added an additional commit with more details. Regarding editors and such, I added a paragraph detailing what I would use for each operating system and what I used for the purposes of writing the article.

I wish a rubygems or rust crates or python eggs existed for C++. It doesn't exist in a standard way, and differs for each operating system and flavor of operating system.

`#pragma once` is indeed common enough that it shouldn't need mention (it prevents the file from being expanded more than once by the preprocessor).

**Comment by tsloughter** [comment]
Woo, this is looking great. And if I haven't mentioned before, I really like the example used :). I'm going to get it merged in and up on howistart-staging.herokuapp.com later today for a final reviewing to verify how it looks after deploying. I'll ping you when it is up on staging so you can check too.

**Comment by jeremyong** [comment]
Awesome, I'll wait for your ping then, and glad you like the example :+1: 

I wanted to do some a little weirder than what people may have seen, or at least demystify what they have seen with other programming languages that do it.

**Pull request merged**
